### ISSUE TITLE
Failed to test real-time endpoint

### ISSUE THREAD

**Issue by earnings84** [MicrosoftLearning/AI-900-AIFundamentals#10]
# Module: Explore clustering with Azure Machine Learning Designer
#### Step: 2

Description of issue
the following code-
{
     "Inputs": {
         "WebServiceInput0": [
             {
                 "CulmenLength": 49.1,
                 "CulmenDepth": 4.8,
                 "FlipperLength": 1220,
                 "BodyMass": 5150
             }
         ]
     },
     "GlobalParameters":  {}
 }

-------------gives this error--->
Failed to test real-time endpoint
{"error":{"code":400,"message":"Input Data Error. Input data are inconsistent with schema.\nSchema: {'input1': '1:Dataset'}\nData: {'WebServiceInput0': defaultdict(<class 'list'>, {'CulmenLength': [49.1], 'CulmenDepth': [4.8], 'FlipperLength': [1220], 'BodyMass': [5150]})}\nNoneType: None\n","details":""}}
--------------------------------------
Hence, the error can be corrected by -->
{
  "Inputs": {
    "input1": [
      
      {
        "CulmenLength": 49.1,
        "CulmenDepth": 4.8,
        "FlipperLength": 1220,
        "BodyMass": 5150
      }
      
    ]
  },
  "GlobalParameters": {}
}

**Comment by sherzyang** [comment]
@earnings84 thanks for sharing, I have pushed an update to fix the issue.
