### ISSUE TITLE
02b-create-classification-model.md: "PatientID" used as a feature

### ISSUE THREAD

**Issue by jhauffa** [MicrosoftLearning/AI-900-AIFundamentals#12]
# Module: AI-900
#### Step: 2

Description of issue:

The pipeline does not contain a "Select Columns in Dataset" transformation module, so the model is trained on all columns of the dataset, including "PatientID". This is bad practice, since we know that there is no causal relationship between the ID and the diagnosis. In my tests, the model appears to pick up on a negative correlation between ID and diagnosis: by increasing/decreasing the ID and leaving all other inputs unchanged, one can "flip" the decision of the classifier.

The student should be instructed to add a "Select Columns in Dataset" module to the pipeline (analogous to the previous notebook 02a), which selects all columns except "PatientID".

Repro steps:

1. Follow the instructions in the notebook until you reach the task "Test the service".
2. Use the provided test data to make a prediction. Observe that the prediction is positive ("1") with a probability of ~0.7.
3. In the test data, change the value of "PatientID" from 1882185 to 18821850; leave all other values as they are. Observe that the prediction is now negative ("0") with a probability of ~0.13.

**Comment by sherzyang** [comment]
Thanks @jhauffa, you bring up a good point. I'll push an update to remove the PatientID feature from the model.
