### ISSUE TITLE
AI-900-02b Add transformations : Select Columns / Remove PatientID step is missing

### ISSUE THREAD

**Issue by derKosi** [MicrosoftLearning/AI-900-AIFundamentals#18]
# Module: AI-900
#### Step: 2 - 3

Description of issue
I think that not there is a step missing like 
'add all but pationt ID columns to select columns'
maybe even with images and things.

Double click on the **Select Columns in Dataset** module to access a settings pane on the right. Select **Edit column**. Then in the **Select columns** window, select **By name** and **Add all** to add all the columns. Then remove **PatientID**, so your final column selection looks like this:

![image](https://user-images.githubusercontent.com/5459382/214316870-3049b390-00d6-4c3e-8762-8874b0383722.png)

**Comment by derKosi** [comment]
Also,

Click on the **Save** button.

**Comment by derKosi** [comment]
Also,
the next step (5) is not quite working,

since one cannot use 'By name' in 'Columns to transform' if one has not 'build the pipeline' or 'submitted the design',  

![image](https://user-images.githubusercontent.com/5459382/214318142-9830b5a3-3020-4646-8c5e-6ee1c05a0915.png)

**Comment by sherzyang** [comment]
Thank you @derKosi! I will go ahead and update based on what you shared.
