### ISSUE TITLE
AI-900-02b Create an inference pipeline: 

### ISSUE THREAD

**Issue by derKosi** [MicrosoftLearning/AI-900-AIFundamentals#19]
# Module: AI-900
#### Step: 05

Description of issue

1. The pipeline does not automatically include a **Web Service Input** component for models created from custom data sets. Search for a **Web Service Input** component from the asset library and place it at the top of the pipeline. Connect the output of the **Web Service Input** component to the right-side input of the **Apply Transformation** component that is already on the canvas.

should be

1. The pipeline does not automatically include a **Web Service Input** component for models created from custom data sets. Search for a **Web Service Input** component from the asset library and place it at the top of the pipeline. Connect the output of the **Web Service Input** component to input of the **Select Columns in Dataset** component that is already on the canvas.

**Comment by sherzyang** [comment]
Thanks @derKosi, I'll push an update!
