### ISSUE TITLE
Create Dataset from web files needs updated instructions

### ISSUE THREAD

**Issue by zeeb33** [MicrosoftLearning/AI-900-AIFundamentals#2]
# Module: 02
### Task: 05

Description of issue
The Datastore and file selection portion of instructions is no longer needed. When creating a Dataset in Azure from web files the user is only required to enter the URL address of that web file for Azure to grab those files. 

![image](https://user-images.githubusercontent.com/42649591/157082258-7ae14e57-3087-40c6-9ff6-32774675fe55.png)
![image](https://user-images.githubusercontent.com/42649591/157082862-a6db28be-fa76-48ca-8ac6-018e15e12f2e.png)

**Comment by sherzyang** [comment]
Thanks @zbskillable! I just asked for the content to be republished with an update based on the UI changes you shared.
