### ISSUE TITLE
Error when running analyze-image.ps in Azure Cloud Shell

### ISSUE THREAD

**Issue by charleswhchan** [MicrosoftLearning/AI-900-AIFundamentals#27]
# Module: [Analyze images with the Computer Vision service](https://learn.microsoft.com/en-ca/training/modules/analyze-images-computer-vision/)
#### Step: 6

Description of issue
When running the script in Azure Cloud Shell, received the follow error
```
PS /home/user1-30332935/ai-900> ./analyze-image.ps1 store-camera-1.jpg
Analyzing image...
Invoke-RestMethod: /home/user1-30332935/ai-900/analyze-image.ps1:21
Line |
  21 |  $result = Invoke-RestMethod -Method Post `
     |            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | {"error":{"code":"404","message": "Resource not found"}}
ConvertFrom-Json: /home/user1-30332935/ai-900/analyze-image.ps1:26
Line |
  26 |  $analysis = $result | ConvertFrom-Json
     |                        ~~~~~~~~~~~~~~~~
     | Cannot bind argument to parameter 'InputObject' because it is null.

Description:

Objects in this image:

Tags relevant to this image:

```

Repro steps:
Follow the instructions in the lab.
PowerShell Version: 7.3.3

**Comment by Mihai-Ac** [comment]
Hello @charleswhchan ,
I have ran through the lab two times (in two different VMs) and could not reproduce this error.
![image](https://user-images.githubusercontent.com/110993710/232826807-ccc02fa9-136f-4468-be72-1359c2e2be2d.png)



Have you tried restarting the cloud shell session and trying again? Does the error still occur? What about restarting the training session, doing that still raises this error?

Best regards,
Mihai

**Comment by charleswhchan** [comment]
@Mihai-Ac : are there any command(s) that I can run within Cloud Shell to capture more information for debugging?

**Comment by charleswhchan** [comment]
Works again after I restart the training session. So likely operator error. 😅
