### ISSUE TITLE
Button in the Deploy a model menu to deploy the model doesn't work

### ISSUE THREAD

**Issue by teriaavibes** [MicrosoftLearning/AI-900-AIFundamentals#29]
# Module: 02
#### Step: 03

Description of issue

Button in the Deploy a model doesn't work/do anything after pressing it while trying to deploy a model. Not the only one encountering issue with this step.  https://www.reddit.com/r/AzureCertification/comments/13cy5no/ai900_first_lab_does_not_create_the_azure/

<img width="644" alt="image" src="https://github.com/MicrosoftLearning/AI-900-AIFundamentals/assets/68708075/50c365fe-1483-459f-add5-4dc18716617d">

Repro steps:

1. Follow the lab instructions

**Comment by Mihai-Ac** [comment]
Hello,
I followed all steps and couldn´t reproduce the issue. The **Deploy** button worked and I could finish the lab without issues.
Have you tried going through a new deployment to see if the error continues? How about a different browser?

Best regards,
Mihai

**Comment by teriaavibes** [comment]
Hi,

I have run this through the Skillable Learn on Demand labs which only contain Microsoft Edge as browser to my knowledge. I have tried it two times just to be sure I will try a different lab provider if it makes a difference.

**Comment by sherzyang** [comment]
Thanks @teriaavibes and @Mihai-Ac. I will share this bug with the Azure ML product team as it is not a lab-specific issue.
