### ISSUE TITLE
Image Visualization contradicts step by step guide 

### ISSUE THREAD

**Issue by JayDii** [MicrosoftLearning/AI-900-AIFundamentals#32]
# Module: instructions/02b-create-classification-model.md
#### Step: 5 and 7

Description of issue

The Image (instructions/media/create-classification-model/inference-changes.png) shows the Modules "Enter Data Manually" and "Web Service Input" to be connected to the "Select Columns in Datasets" Input. Whereas the instruction says to connect them to the "Apply Transformations Module".

> Connect the output of the Web Service Input component to the right-side input of the **Apply Transformation** component that is already on the canvas.

I might be missing something. But i guess it should say: "Connect the output of the Web Service Input component to the right-side input of the **Select Columns in Datasets** component that is already on the canvas

Regards
Jan

P.S. My first ever GitHub Issue. I hope did it correctly.

**Comment by sherzyang** [comment]
@JayDii thanks so much for logging this issue! Your description helped me fix the issue. You should see the change reflected in the instructions now.
