### ISSUE TITLE
Face APIs no longer supported

### ISSUE THREAD

**Issue by pjirsa** [MicrosoftLearning/AI-900-AIFundamentals#33]
# Module: Explore Face Recognition
#### Step: 6

Description of issue
This module provides instructions to create a Cognitive Services resource for use with a face-detection sample. However, I receive the following error message when running the script:
```
Line |
  22 |  $result = Invoke-RestMethod -Method Post `
     |            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Face APIs are not supported for Cognitive Service resources created after 06/21/2022"
```

**Comment by sherzyang** [comment]
Thanks @pjirsa for identifying this issue!
