### ISSUE TITLE
05-create-cognitive-search-solution[does query work?]

### ISSUE THREAD

**Issue by nobuhiro-yamada** [MicrosoftLearning/AI-900-AIFundamentals#35]
# 05-create-cognitive-search-solution

## The query below did not return correct results.
search=$filter=locations eq 'Chicago'
search=$filter=sentiment eq 'negative'

## The query below returned correct results.
search=locations:'Chicago'
search=sentiment:'negative'

**Comment by sherzyang** [comment]
Thanks so much @nobuhiro-yamada, I tested and will push the fix you suggested!
