### ISSUE TITLE
02a - Create Regression Model.md

### ISSUE THREAD

**Issue by srgopal** [MicrosoftLearning/AI-900-AIFundamentals#36]
# Module: AI-900-AllFundamentals
#### Step: 02

Description of issue
Unable to select 'Automobile price data (Raw)' dataset onto the canvas.

Repro steps:
None. This dataset doesn't seem to have been loaded as a Data Asset, in the previous steps.

**Comment by sherzyang** [comment]
Thanks @srgopal, you will want to click on "Component" to select the Automobile price data (Raw) onto the canvas. It is one of the prebuilt datasets. 

![image](https://github.com/MicrosoftLearning/AI-900-AIFundamentals/assets/19577448/4a1576a7-8340-4204-8cc0-85a0e81490b3)
