### ISSUE TITLE
New lay-out of the Designer in Machine Learning Studio

### ISSUE THREAD

**Issue by tdebusscher** [MicrosoftLearning/AI-900-AIFundamentals#38]
# URL: https://microsoftlearning.github.io/AI-900-AIFundamentals/instructions/02a-create-regression-model.html
# Module: Create a pipeline in Designer
#### Step: 2 to 5

Description of issue:
The designer got a new lay-out and step 2 to 5 under 'Create a pipeline in Designer' aren't in line with the current designer anymore. See attachments at the bottom.

Proposition for new steps after current step 1:
2. At the top right-hand side of the screen, select Configure & Submit.
3. In the side bar under step 1 Basics, change the draft name (Pipeline-Created-on-date) to Auto Price Training. Click at the bottom on Next.
4. In step 2 Inputs & Outputs click Next again
5. In step 3 Runtime settings under Select compute type, select Compute cluster. Then under Select Azure ML compute cluster, select the compute cluster you created previously. Click at the bottom on Next.
6. In step 4 Review + Submit click on Submit at the bottom.

Attachments:
create-pipeline-help-current.png  -> current image under this step on the URL managed above
![create-pipeline-help-current](https://github.com/MicrosoftLearning/AI-900-AIFundamentals/assets/116720402/a3684e26-0302-400f-94ba-0f348499fc57)
create-pipeline-help-new.png -> screenshot of new lay-out
![create-pipeline-help-new](https://github.com/MicrosoftLearning/AI-900-AIFundamentals/assets/116720402/f13ce557-506a-404f-96b6-979dea1bdb29)

**Comment by sherzyang** [comment]
Hi @tdebusscher, thanks for bringing this up. I'm sharing with @GraemeMalcolm.
