### ISSUE TITLE
Can't edit pipeline that has been submitted and run

### ISSUE THREAD

**Issue by HairyDrumroll** [MicrosoftLearning/AI-900-AIFundamentals#45]
# Module: Create a regression model with Azure Machine Learning designer
#### Step: 1. Return to the pipeline you created

Description of issue
After running the pipeline which prepares the dataset for model training I am unable to edit the pipeline again without cloning it first - this is if I select the pipeline through the 'Jobs' list under 'Assets' in the menu group on the left.

The documentation should direct users to go to the 'Designer' option under the 'Authoring' group.

Documentation source: [instructions/02a-create-regression-model.md](https://github.com/MicrosoftLearning/AI-900-AIFundamentals/blob/1d89241250838553abf3382c0afadbaad8683ba9/instructions/02a-create-regression-model.md)

Repro steps:

1. Create pipeline, add transformations, run pipeline.
1. Return to pipeline created in previous step
1. Am now unable to edit pipeline, only option is to clone and make edits to clone.

**Comment by HairyDrumroll** [comment]
Same problem when I get to [Evaluate Model](https://microsoftlearning.github.io/AI-900-AIFundamentals/instructions/02a-create-regression-model.html#evaluate-model)

**Comment by HairyDrumroll** [comment]
I'm also not clear on the difference between steps 6 & 7 under the heading [Evaluate Model](https://microsoftlearning.github.io/AI-900-AIFundamentals/instructions/02a-create-regression-model.html#evaluate-model)

**Comment by HairyDrumroll** [comment]
And it would be good to include a description of what an [Inference Pipeline](https://microsoftlearning.github.io/AI-900-AIFundamentals/instructions/02a-create-regression-model.html#create-and-run-an-inference-pipeline) actually is or what it does.
Also, the Python code has an extra return and indentation which causes problems when the code is run.
It should be as follows:

     import pandas as pd

     def azureml_main(dataframe1 = None, dataframe2 = None):

          scored_results = dataframe1[['Scored Labels']]
          scored_results.rename(columns={'Scored Labels':'predicted_price'},inplace=True)
          return scored_results

**Comment by John-Vance** [comment]
I can confirm the Python code as given in the training module fails and that @HairyDrumroll's version works. Here's the error when using the original:

`Execution failed. User process '/azureml-envs/azureml_8f317849db35f281450cf74333640b98/bin/python' exited with status code 1. Please check log file 'user_logs/std_log.txt' for error details. Error:     ModuleReflector(parser.module_entry, env).exec(
  File "/azureml-envs/azureml_8f317849db35f281450cf74333640b98/lib/python3.8/site-packages/azureml/studio/modulehost/module_reflector.py", line 397, in exec
    self._handle_exception(bex)
  File "/azureml-envs/azureml_8f317849db35f281450cf74333640b98/lib/python3.8/site-packages/azureml/studio/modulehost/module_reflector.py", line 471, in _handle_exception
    raise exception
  File "/azureml-envs/azureml_8f317849db35f281450cf74333640b98/lib/python3.8/site-packages/azureml/studio/modulehost/module_reflector.py", line 379, in exec
    output_tuple = self._entry.func(**reflected_input_ports, **reflected_parameters)
  File "/azureml-envs/azureml_8f317849db35f281450cf74333640b98/lib/python3.8/site-packages/azureml/studio/modulehost/module_reflector.py", line 76, in wrapper
    ret = func(*args, **validated_args)
  File "/azureml-envs/azureml_8f317849db35f281450cf74333640b98/lib/python3.8/site-packages/azureml/studio/modules/python_language_modules/execute_python_script.py", line 126, in run
    return _run_impl(**input_values)
  File "/azureml-envs/azureml_8f317849db35f281450cf74333640b98/lib/python3.8/site-packages/azureml/studio/modules/python_language_modules/execute_python_script.py", line 216, in _run_impl
    ErrorMapping.throw(executing_script_error)
  File "/azureml-envs/azureml_8f317849db35f281450cf74333640b98/lib/python3.8/site-packages/azureml/studio/common/error.py", line 835, in throw
    raise err
azureml.studio.common.error.FailedToEvaluateScriptError: The following error occurred during script evaluation, please view the output log for more information:
---------- Start of error message from Python interpreter ----------
Got exception when invoking script: 'IndentationError: unexpected indent (user_script_8ca2342671e34bb0bf50fe17714f4eb4.py, line 1)'.
---------- End of error message from Python  interpreter  ----------`

**Comment by sherzyang** [comment]
@HairyDrumroll, thanks for bringing these issues up. Let me go through them one by one. 
**Topic 1** - unable to edit pipeline. 

It sounds like the UI got a bit of an update and my instructions could be clearer. I will update the instructions with directions to return to the pipeline by selecting designer>pipelines.
The edit issue occurs if you stay on the "jobs" tab. 
![image](https://github.com/MicrosoftLearning/AI-900-AIFundamentals/assets/19577448/59d82cfc-54e3-44b2-9298-48d1d3690437)

If you go back to the designer page, you can select your pipeline and continue to edit it. 
![image](https://github.com/MicrosoftLearning/AI-900-AIFundamentals/assets/19577448/a9b2213f-b3d4-4d44-a4db-9c834f9626e8)

Sounds like the same issue for *Evaluate Model*. Hope this resolves both.

**Comment by sherzyang** [comment]
**Topic 2** - steps 6 & 7 in Evaluate Model section repeat. I have removed the repeat. Thanks for identifying that.

**Comment by sherzyang** [comment]
**Topic 3** - more information on inference pipelines would be helpful. 
Totally, you can find more information here. What is covered is out of scope for AI-900 but is covered in [DP-100](https://learn.microsoft.com/en-us/training/modules/deploy-model-batch-endpoint/). 
https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/innovate/best-practices/ml-deployment-inference

**Comment by sherzyang** [comment]
Topic 4 - @HairyDrumroll @John-Vance , yes, there is an issue with the copy and paste adding an extra space in the python script. Thanks for bringing that to my attention. I will add a note for users to be aware that might be an issue.
