### ISSUE TITLE
Replace Azure AI Services instead of Cognitive Services

### ISSUE THREAD

**Issue by suketunayak** [MicrosoftLearning/AI-900-AIFundamentals#47]
# Module: 03
#### Step: 00

Description of issue - Replace Azure AI Services instead of Cognitive Services in all Labs steps

![image](https://github.com/MicrosoftLearning/AI-900-AIFundamentals/assets/12823966/62d94cde-8ff2-4c79-a108-65d62d4a1c56)

**Comment by sherzyang** [comment]
Thanks @suketunayak. I will update the instructions partially. Users should create an Azure AI services resource by searching for Cognitive Services, selecting "create Cognitive Services", which will then take users to a page for creating an Azure AI service. The product is being updated. At the moment, if you search for "Azure AI services" in the marketplace, it is not possible to locate that resource. Please let me know if you have a different experience.

**Comment by sherzyang** [comment]
I've made the following changes and will take a scrub through the other content. Additionally, I will open a ticket to ask for the portal experience to fully align with product naming updates. Thanks!
![image](https://github.com/MicrosoftLearning/AI-900-AIFundamentals/assets/19577448/7b5c58d4-497b-485a-908c-cd5b2aa2201b)

**Comment by suketunayak** [comment]
Hi

Please refer below screenshot, When we search for cognitive services nothing coming with name starting cognitive.


[cid:74fdc723-a23e-4716-8aaf-9c53d9a6ea43]
![image](https://github.com/MicrosoftLearning/AI-900-AIFundamentals/assets/12823966/5aaffcbb-268a-4ced-82ee-89eb17a4a7cb)


Thanks for quick help and support.


Thanking You,

Suketu Nayak
MCT



________________________________

**Comment by suketunayak** [comment]
Hi

When we search Azure AI Services in marketplace directly that works: Please refer below screenshot

![image](https://github.com/MicrosoftLearning/AI-900-AIFundamentals/assets/12823966/870c6d8d-fbd5-486d-b671-76b4e2b7d2e2)


Thanks

**Comment by sherzyang** [comment]
@suketunayak yes, I submitted a bug and engineers updated the marketplace to allow for "Azure AI services" search in the marketplace. I have updated all the labs to use Azure AI services and removed mentions of Cognitive Services. Thanks!
