### ISSUE TITLE
Lab 1: UI update changes anomaly detector creation

### ISSUE THREAD

**Issue by SkillableBB** [MicrosoftLearning/AI-900-AIFundamentals#49]
#### Step: 02

Description of issue

The UI in the Azure portal for Anomaly detector has been updated, which has removed it from availability in create resources [p1], and you can no longer create anomaly detectors on its own blade/page in Azure portal [p2].

[p1]

![image](https://github.com/MicrosoftLearning/AI-900-AIFundamentals/assets/94069201/43cace74-c609-4f68-b6ae-3330a9ea5eda)

[p2]
Prior version:

![image](https://github.com/MicrosoftLearning/AI-900-AIFundamentals/assets/94069201/ab1769e9-58cf-4072-bc6f-6fc769f48972)

Updated: 

![image](https://github.com/MicrosoftLearning/AI-900-AIFundamentals/assets/94069201/b015cf3a-ae30-42fd-93a1-a40108cc47d9)

**Comment by cloudtrainerwork** [comment]
Until that is resolved here is some Powershell as a workaround
````powershell
az cognitiveservices account create --name myresource --resource-group myResourceGroup --kind AnomalyDetector --sku S0 --location EastUS --yes
`````

**Comment by sherzyang** [comment]
@cloudtrainerwork , thanks for the workaround. We are going to work to retire this lab and replace with a new one.

**Comment by sherzyang** [comment]
@cloudtrainerwork, @SkillableBB, we have decided to deprecate the lab. It will be replaced with a new one. You can see the current message here: https://github.com/MicrosoftLearning/AI-900-AIFundamentals/blob/main/instructions/01-module-01.md.

**Comment by texnomore** [comment]
@sherzyang - With the removal of Lab 1 - would you consider that the remaining labs cover all the necessary learning? We had a client that had issues with the lab, and we are doing a follow up lab session with them, but want to be assured that they will be learning all they need to in order to prepare for the certification. Thank you!
