### ISSUE TITLE
README File 

### ISSUE THREAD

**Issue by iemejia** [MicrosoftLearning/AI-900-AIFundamentals#5]
The README file includes this link [Download Latest Student Handbook and AllFiles Content](https://github.com/MicrosoftLearning/AI-900-AIFundamentals/releases/latest) but there is no content once you click it.
<img width="1301" alt="Screenshot 2022-07-14 at 07 21 27" src="https://user-images.githubusercontent.com/79476/178905495-5fdb5e6c-30db-4acf-8e07-dd455cb2de9f.png">

**Comment by sherzyang** [comment]
@iemejia thanks for calling attention to that dead link. I updated the readme and removed the link. The student handbook is available for download in the MCT portal.
