### ISSUE TITLE
AI-900 | lab 1 - Anomaly Detector 

### ISSUE THREAD

**Issue by CharityDavis** [MicrosoftLearning/AI-900-AIFundamentals#50]
# Module: Anomaly Detector
#### Step: 00

Description of issue
Known issue -- The create icon for the anomaly detector in the lab was missing and therefore the students couldn't complete lab 1.

Question:
If the students completed the other labs in the module, will they have acquired the knowledge necessary for AI-900?

**Comment by sherzyang** [comment]
Great question @CharityDavis, yes. This lab's purpose was to get students introduced to the process of creating an Azure AI service resource and using it. They get a similar experience with other labs. We are also in the process of refreshing all the labs in the next month for an updated experience.
