### ISSUE TITLE
AI-900-AIFundamentals/instructions/02a-create-regression-model - Incorrect Python code

### ISSUE THREAD

**Issue by OscarValerock** [MicrosoftLearning/AI-900-AIFundamentals#55]
AI-900-AIFundamentals/instructions/02a-create-regression-model.html

Description of issue: Python incorrect on Create and run an inference pipeline Step 9 is incorrect.  Code should have an indented return: 

```
import pandas as pd

def azureml_main(dataframe1=None, dataframe2=None):
    scored_results = dataframe1[['Scored Labels']]
    scored_results.rename(columns={'Scored Labels': 'predicted_price'}, inplace=True)
    return scored_results
```

I've already left a comment on the commit where the change was done. Tagging: @sherzyang

**Comment by Mihai-Ac** [comment]
Hello @OscarValerock 

Thanks for flagging. I created a PR with a fix for this issue.

Regards,
Mihai

**Comment by sherzyang** [comment]
Thanks @Mihai-Ac, @OscarValerock, I've merged the fix.
